config/routes.rb
Rails.application.routes.draw do
  resources :cachorros
  resources :pessoas

end

app/models/cachorro.rb
class Cachorro < ActiveRecord::Base
	validates :nome, :data_de_nascimento, :porte, :sexo, :saude, :temperamento, :equipamento, :frequencia_de_passeio, :tempo_de_passeio, presence: true
end

app/models/pessoa.rb
class Pessoa < ActiveRecord::Base
	validates :nome, :data_de_nascimento, :email, :telefone, presence: true
	validates :email, uniqueness: true
	validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
	validates :foto, allow_blank: true, format: {
		with: %r{\.(jpg|png)\Z}i,
		message: 'A imagem deve estar no formato .jpg ou .png.'
	}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cachorros_controller.rb
class CachorrosController < ApplicationController
  before_action :set_cachorro, only: [:show, :edit, :update, :destroy]

  # GET /cachorros
  def index
    @cachorros = Cachorro.all
  end

  # GET /cachorros/1
  def show
  end

  # GET /cachorros/new
  def new
    @cachorro = Cachorro.new
  end

  # GET /cachorros/1/edit
  def edit
  end

  # POST /cachorros
  def create
    @cachorro = Cachorro.new(cachorro_params)

    if @cachorro.save
      redirect_to @cachorro, notice: 'Cachorro was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /cachorros/1
  def update
    if @cachorro.update(cachorro_params)
      redirect_to @cachorro, notice: 'Cachorro was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /cachorros/1
  def destroy
    @cachorro.destroy
    redirect_to cachorros_url, notice: 'Cachorro was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cachorro
      @cachorro = Cachorro.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def cachorro_params
      params.require(:cachorro).permit(:nome, :data_de_nascimento, :data_aproximada, :porte, :sexo, :saude, :temperamento, :foto, :equipamento, :dupla_para_passeio_id, :frequencia_de_passeio, :tempo_de_passeio, :habilitado_para_passeio)
    end
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :set_pessoa, only: [:show, :edit, :update, :destroy]

  # GET /pessoas
  def index
    @pessoas = Pessoa.all
  end

  # GET /pessoas/1
  def show
  end

  # GET /pessoas/new
  def new
    @pessoa = Pessoa.new
  end

  # GET /pessoas/1/edit
  def edit
  end

  # POST /pessoas
  def create
    @pessoa = Pessoa.new(pessoa_params)

    if @pessoa.save
      redirect_to @pessoa, notice: 'Parabéns! Seus dados foram armazenados.'
    else
      render :new
    end
  end

  # PATCH/PUT /pessoas/1
  def update
    if @pessoa.update(pessoa_params)
      redirect_to @pessoa, notice: 'Dados pessoais atualizados.'
    else
      render :edit
    end
  end

  # DELETE /pessoas/1
  def destroy
    @pessoa.destroy
    redirect_to pessoas_url, notice: 'Cadastro excluído.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def pessoa_params
      params.require(:pessoa).permit(:nome, :data_de_nascimento, :email, :telefone, :foto)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cachorros_helper.rb
module CachorrosHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/views/cachorros/_form.html.erb
<%= form_for(@cachorro) do |f| %>
  <% if @cachorro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cachorro.errors.count, "error") %> prohibited this cachorro from being saved:</h2>

      <ul>
      <% @cachorro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :data_de_nascimento %><br>
    <%= f.datetime_select :data_de_nascimento %>
  </div>
  <div class="field">
    <%= f.label :data_aproximada %><br>
    <%= f.check_box :data_aproximada %>
  </div>
  <div class="field">
    <%= f.label :porte %><br>
    <%= f.text_field :porte %>
  </div>
  <div class="field">
    <%= f.label :sexo %><br>
    <%= f.text_field :sexo %>
  </div>
  <div class="field">
    <%= f.label :saude %><br>
    <%= f.text_field :saude %>
  </div>
  <div class="field">
    <%= f.label :temperamento %><br>
    <%= f.text_field :temperamento %>
  </div>
  <div class="field">
    <%= f.label :foto %><br>
    <%= f.text_field :foto %>
  </div>
  <div class="field">
    <%= f.label :equipamento %><br>
    <%= f.text_field :equipamento %>
  </div>
  <div class="field">
    <%= f.label :dupla_para_passeio_id %><br>
    <%= f.number_field :dupla_para_passeio_id %>
  </div>
  <div class="field">
    <%= f.label :frequencia_de_passeio %><br>
    <%= f.number_field :frequencia_de_passeio %>
  </div>
  <div class="field">
    <%= f.label :tempo_de_passeio %><br>
    <%= f.number_field :tempo_de_passeio %>
  </div>
  <div class="field">
    <%= f.label :habilitado_para_passeio %><br>
    <%= f.check_box :habilitado_para_passeio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cachorros/edit.html.erb
<h1>Editing Cachorro</h1>

<%= render 'form' %>

<%= link_to 'Show', @cachorro %> |
<%= link_to 'Back', cachorros_path %>

app/views/cachorros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cachorros</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Data de nascimento</th>
      <th>Data aproximada</th>
      <th>Porte</th>
      <th>Sexo</th>
      <th>Saude</th>
      <th>Temperamento</th>
      <th>Foto</th>
      <th>Equipamento</th>
      <th>Dupla para passeio</th>
      <th>Frequencia de passeio</th>
      <th>Tempo de passeio</th>
      <th>Habilitado para passeio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cachorros.each do |cachorro| %>
      <tr>
        <td><%= cachorro.nome %></td>
        <td><%= cachorro.data_de_nascimento %></td>
        <td><%= cachorro.data_aproximada %></td>
        <td><%= cachorro.porte %></td>
        <td><%= cachorro.sexo %></td>
        <td><%= cachorro.saude %></td>
        <td><%= cachorro.temperamento %></td>
        <td><%= cachorro.foto %></td>
        <td><%= cachorro.equipamento %></td>
        <td><%= cachorro.dupla_para_passeio_id %></td>
        <td><%= cachorro.frequencia_de_passeio %></td>
        <td><%= cachorro.tempo_de_passeio %></td>
        <td><%= cachorro.habilitado_para_passeio %></td>
        <td><%= link_to 'Show', cachorro %></td>
        <td><%= link_to 'Edit', edit_cachorro_path(cachorro) %></td>
        <td><%= link_to 'Destroy', cachorro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cachorro', new_cachorro_path %>

app/views/cachorros/new.html.erb
<h1>New Cachorro</h1>

<%= render 'form' %>

<%= link_to 'Back', cachorros_path %>

app/views/cachorros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cachorro.nome %>
</p>

<p>
  <strong>Data de nascimento:</strong>
  <%= @cachorro.data_de_nascimento %>
</p>

<p>
  <strong>Data aproximada:</strong>
  <%= @cachorro.data_aproximada %>
</p>

<p>
  <strong>Porte:</strong>
  <%= @cachorro.porte %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @cachorro.sexo %>
</p>

<p>
  <strong>Saude:</strong>
  <%= @cachorro.saude %>
</p>

<p>
  <strong>Temperamento:</strong>
  <%= @cachorro.temperamento %>
</p>

<p>
  <strong>Foto:</strong>
  <%= @cachorro.foto %>
</p>

<p>
  <strong>Equipamento:</strong>
  <%= @cachorro.equipamento %>
</p>

<p>
  <strong>Dupla para passeio:</strong>
  <%= @cachorro.dupla_para_passeio_id %>
</p>

<p>
  <strong>Frequencia de passeio:</strong>
  <%= @cachorro.frequencia_de_passeio %>
</p>

<p>
  <strong>Tempo de passeio:</strong>
  <%= @cachorro.tempo_de_passeio %>
</p>

<p>
  <strong>Habilitado para passeio:</strong>
  <%= @cachorro.habilitado_para_passeio %>
</p>

<%= link_to 'Edit', edit_cachorro_path(@cachorro) %> |
<%= link_to 'Back', cachorros_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vagrant</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pessoas/_form.html.erb
<%= form_for(@pessoa) do |f| %>
  <% if @pessoa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
      <% @pessoa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :data_de_nascimento %><br>
    <%= f.date_select :data_de_nascimento %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :foto %><br>
    <%= f.text_field :foto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pessoas/edit.html.erb
<h1>Editing Pessoa</h1>

<%= render 'form' %>

<%= link_to 'Show', @pessoa %> |
<%= link_to 'Back', pessoas_path %>

app/views/pessoas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pessoas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Data de nascimento</th>
      <th>Email</th>
      <th>Telefone</th>
      <th>Foto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pessoas.each do |pessoa| %>
      <tr>
        <td><%= pessoa.nome %></td>
        <td><%= pessoa.data_de_nascimento %></td>
        <td><%= pessoa.email %></td>
        <td><%= pessoa.telefone %></td>
        <td><%= pessoa.foto %></td>
        <td><%= link_to 'Show', pessoa %></td>
        <td><%= link_to 'Edit', edit_pessoa_path(pessoa) %></td>
        <td><%= link_to 'Destroy', pessoa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pessoa', new_pessoa_path %>

app/views/pessoas/new.html.erb
<h1>New Pessoa</h1>

<%= render 'form' %>

<%= link_to 'Back', pessoas_path %>

app/views/pessoas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @pessoa.nome %>
</p>

<p>
  <strong>Data de nascimento:</strong>
  <%= @pessoa.data_de_nascimento %>
</p>

<p>
  <strong>Email:</strong>
  <%= @pessoa.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @pessoa.telefone %>
</p>

<p>
  <strong>Foto:</strong>
  <%= @pessoa.foto %>
</p>

<%= link_to 'Edit', edit_pessoa_path(@pessoa) %> |
<%= link_to 'Back', pessoas_path %>